### ISSUE TITLE
Tracking Future Work

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/course_reserves#23]
- [ ] Server provisioning (stage/prod, shibboleth)
- [ ] Migrate app to use shibboleth
- [x] Merge #20
- [x] Add some sort of support for sorting columns on the homepage (e.g. datatables?)
- [x] Refactor cloning workflow to always clone from a known reserve ID and not use the compound ID and pick the first list.
